version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: accounts_api_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      DATABASE_URL: ecto://postgres:postgres@db/accounts_api_dev

volumes:
  postgres_data:

